prima: Fix for loop has empty body
Silence these warnings:

../CORE/HDD/src/wlan_hdd_cfg.c:4096:43: error: for loop has empty body [-Werror,-Wempty-body]
   for (ptr = str; i_isspace(*ptr); ptr++);
                                          ^
../CORE/HDD/src/wlan_hdd_cfg.c:4096:43: note: put the semicolon on a separate line to silence this warning
../CORE/HDD/src/wlan_hdd_cfg.c:4105:48: error: for loop has empty body [-Werror,-Wempty-body]
   for (; ptr != str && i_isspace(*ptr); ptr--);
                                               ^
../CORE/HDD/src/wlan_hdd_cfg.c:4105:48: note: put the semicolon on a separate line to silence this warning

Signed-off-by: khusika <khusikadhamar@gmail.com>
[kras: Little fix to commit message]
Signed-off-by: Albert I <kras@raphielgang.org>
(cherry picked from commit 6b28ed0705498a8a03ce0368eb7529dfd52dbcf4)
Signed-off-by: GeoPD <geoemmanuelpd2001@gmail.com>